syntax on
set tabstop=4
set hls
set colorcolumn=80
set encoding=utf-8
set ruler
set nonu

let branchname = system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
let branch = strlen(branchname) > 0?' |'.branchname.'| ':' '
colorscheme delek

map <C-K> :pyf /usr/local/llvm39/share/clang/clang-format.py<cr>
imap <C-K> <c-o>:pyf /usr/local/llvm39/share/clang/clang-format.py<cr>

" http://www.alexeyshmalko.com/2014/using-vim-as-c-cpp-ide/
" ! mark prevents Vim from jumping to location of first error found
nnoremap <F4> :make!<cr>
nnoremap <silent> <F5> :let _s=@/ <Bar> :%s/\s\+$//e <Bar> :let @/=_s <Bar> :nohl <Bar> :unlet _s <CR>
set makeprg=gmake

if has('gui_running')
	set list listchars=tab:>-,nbsp:.,trail:.,extends:>,precedes:<,eol:\|
	let &showbreak = '^'
else
	set showbreak=+++
	set list listchars=tab:▸\ ,nbsp:∙,trail:∙,extends:▶,precedes:◀,eol:¬
	"let &showbreak='↳'
	"set showbreak='↳'
	"set showbreak='¬'
	"set showbreak='↵'
	"set showbreak='␤'
	"set showbreak='↲'
	"set list listchars=tab:▸\ ,nbsp:∙,trail:∙,extends:▶,precedes:◀,eol:↳
	"set list listchars=tab:▸\ ,nbsp:∙,trail:∙,eXtends:▶,precedes:◀,eol:¬

	"highlight NonText ctermfg=White
	"highlight SpecialKey ctermfg=White
	highlight SpecialKey ctermfg=darkgrey
	highlight NonText ctermfg=magenta
	highlight Visual ctermfg=Magenta
endif
"highlight DiffAdd    cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffDelete cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffChange cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffText   cterm=bold ctermfg=10 ctermbg=88 gui=none guifg=bg guibg=Red
"highlight DiffAdd    ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffDelete ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffChange ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
"highlight DiffText   ctermfg=10 ctermbg=88 gui=none guifg=bg guibg=Red

set nolist
set laststatus=2
set showtabline=2

if &diff
	highlight Normal term=none cterm=none ctermfg=White ctermbg=Black gui=none guifg=White guibg=Black

	highlight DiffAdd cterm=none ctermfg=fg ctermbg=Blue gui=none guifg=fg guibg=Blue
	highlight DiffDelete cterm=none ctermfg=fg ctermbg=Blue gui=none guifg=fg guibg=Blue
	highlight DiffChange cterm=none ctermfg=fg ctermbg=Blue gui=none guifg=fg guibg=Blue
	highlight DiffText cterm=none ctermfg=bg ctermbg=White gui=none guifg=bg guibg=White
endif

set statusline=
set statusline+=%t                               "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'},  "file encoding
set statusline+=%{&ff}]                          "file format
set statusline+=%h                               "help file flag
set statusline+=%m                               "modified flag
set statusline+=%r                               "read only flag
set statusline+=%w                               "preview window flag
set statusline+=%y                               "filetype
set statusline+=%{branch}                        "git branch of cwd when vim loaded
set statusline+=%l(%L):%c(%v%V)\ %o\             "line:column
set statusline+=%b,0x%-8B\                       "current char in decimal and hexadecimal
set statusline+=%=                               "left/right separator
set statusline+=buf%n\ \                         "buffer number
set statusline+=%c,                              "cursor column
set statusline+=%l/%L                            "cursor line/total lines
set statusline+=\ %P                             "percent through file
