syntax on
set tabstop=4
set hls
set colorcolumn=80
set encoding=utf-8

map <C-K> :pyf /usr/local/llvm39/share/clang/clang-format.py<cr>
imap <C-K> <c-o>:pyf /usr/local/llvm39/share/clang/clang-format.py<cr>

" http://www.alexeyshmalko.com/2014/using-vim-as-c-cpp-ide/
" ! mark prevents Vim from jumping to location of first error found
nnoremap <F4> :make!<cr>
set makeprg=gmake

if has('gui_running')
	set list listchars=tab:>-,nbsp:.,trail:.,extends:>,precedes:<,eol:\|
	let &showbreak = '^'
else
	set showbreak=+++
	set list listchars=tab:▸\ ,nbsp:∙,trail:∙,extends:▶,precedes:◀,eol:¬
	"let &showbreak='↳'
	"set showbreak='↳'
	"set showbreak='¬'
	"set showbreak='↵'
	"set showbreak='␤'
	"set showbreak='↲'
	"set list listchars=tab:▸\ ,nbsp:∙,trail:∙,extends:▶,precedes:◀,eol:↳
	"set list listchars=tab:▸\ ,nbsp:∙,trail:∙,eXtends:▶,precedes:◀,eol:¬

	"highlight NonText ctermfg=White
	"highlight SpecialKey ctermfg=White
	highlight SpecialKey ctermfg=darkgrey
	highlight NonText ctermfg=magenta
	highlight Visual ctermfg=Magenta
endif

set nolist
set laststatus=2
set showtabline=2

